#!/bin/bash          
echo Ensure 'classes' directory exists
mkdir classes
echo Compile 'purejavacomm'
javac -d classes -sourcepath ./src -cp lib/jna-3.5.1.jar src/purejavacomm/testsuite/TestSuite.java

